### ISSUE TITLE
Consider a different license

### ISSUE THREAD

**Issue by samwaterbury** [BarCodeReader/SelfReformer#1]
Hi! Thank you for sharing this research and code with the public.

Currently, other popular salient object detection implementations such as [U2-Net](https://github.com/xuebinqin/U-2-Net) and [TRACER](https://github.com/Karel911/TRACER) are licensed under Apache License 2.0. I'm curious if you are committed to the `CC BY-NC-ND 4.0` license or if you are open to considering a more permissive license.

From a practical standpoint, the current license prohibits a lot of folks in the ML community from using (and therefore contributing back to or extending) this work.

**Comment by BarCodeReader** [comment]
Thanks for your advice and interest of this work, we are very likely to loosen the license. Since I do not have any experience in this, I put a relatively tight license here.

I will update and let you know.

**Comment by BarCodeReader** [comment]
@samwaterbury an email sent to you~ 
cheers

**Comment by samwaterbury** [comment]
Thanks again @BarCodeReader!
