### ISSUE TITLE
Pre-trained model on DUTS-TE: [Google]

### ISSUE THREAD

**Issue by zqy1** [BarCodeReader/SelfReformer#13]
It should be in DUTS-TR?

**Comment by BarCodeReader** [comment]
I see your point. What I mean is the checkpoint we provided is for DUTS-TE dataset. It is trained on DUTS-TR of course. :)

**Comment by Mohan259** [comment]
@BarCodeReader can you please provide the checkpoint (trained weights) trained on DUTS-TR dataset as well ?
It would be very helpful.

Thanks in advance
