### ISSUE TITLE
Request for pretrained model on DUTS-TR 

### ISSUE THREAD

**Issue by Mohan259** [BarCodeReader/SelfReformer#14]
Hi Author(s) of SelfReformer,
It is a very interesting paper and thank you for sharing the implementation details.
In the Readme.md section (https://github.com/BarCodeReader/SelfReformer#pretrain-model--pre-calculated-saliency-map),
It is mentioned the pretrained model on DUTS-TE is available.
@BarCodeReader 
Can you please provide the checkpoint (trained weights) trained on DUTS-TR dataset as well ?
It would be very helpful.

Thank you in advance

**Comment by BarCodeReader** [comment]
pre-train model on DUTS-TE means trained on DUTS-TR and for test on DUTS-TE.
sorry for the incorrect info delivered. it is the ckpt file you are looking for.
