### ISSUE TITLE
Training issues.

### ISSUE THREAD

**Issue by LWShowTime** [BarCodeReader/SelfReformer#17]
https://github.com/BarCodeReader/SelfReformer/blob/c95d07e7d97a045d82d5244fc1eb8aea5c0937e8/data/__init__.py#L54
Here I got an exception. 
`ValueError: the input array must have size 3 along channel_axis, got (284, 400)`

**Comment by LWShowTime** [comment]
I think there is no need to do with MASK here, so I just comment this line out and everything goes on well.

**Comment by BarCodeReader** [comment]
Thanks for your info and PR.
For some of the benchmark datasets, their masks are in RGB format so we still need to make sure they are all in grayscale.

I feel a better way to do this is to use PIL and then convert the grayscale to np.array:

`mask = Image.open("mask_file_path").convert("L")`
`mask = np.array(mask)`

**Comment by LWShowTime** [comment]
@BarCodeReader Yes, I found some mask have three dimensions in DUTS-TR, you are right. I guess it's the version of skimage I use. My versions will give out an exception when this line of code met with two dimension. Thanks you for your advice. I finnally handle this by using a if-else statement.

**Comment by BarCodeReader** [comment]
@LWShowTime I will update the code accordingly. Thanks for your info again.
