### ISSUE TITLE
/data/__init__.py 54 MASK = color.rgb2gray(MASK)

### ISSUE THREAD

**Issue by lxlch** [BarCodeReader/SelfReformer#2]
the shape of mask is 2D, why do color.rgb2gray(MASK)

**Comment by BarCodeReader** [comment]
Just to guarantee the MASK is in the correct form.
because RGB can also be a black and white image, I used to have this issue on other tasks.
It won't affect anything if you remove it, also it won't change anything if you keep it.

**Comment by lxlch** [comment]
thanks for you reply, l find that the most of  masks in DUTS dataset are 2D, but there are also some 3D masks in it.
