### ISSUE TITLE
where is the default location of the pre-trained model

### ISSUE THREAD

**Issue by shaoniandelilian** [BarCodeReader/SelfReformer#3]
Hello, what is the default location of the pre-trained model when testing the code

**Comment by BarCodeReader** [comment]
https://github.com/BarCodeReader/SelfReformer/blob/0b4e7cf639bd346ca8cefde1e1ddfce958b19f40/main.py#L26
The pth file is loaded from above line when testing mode is on. So you can place your pth anywhere as long as you can correctly specify the path
