### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by cenchaojun** [BarCodeReader/SelfReformer#4]
thank you for your nice work. Your new idea about the transformer model is very impressive, but I still have some unclear details about the implementation.May I ask you how the visualization of Figure 6 in the paper. print feature?
![image](https://user-images.githubusercontent.com/48192514/189028628-bd232a32-7218-41aa-87b8-412eaedc9f94.png)

**Comment by BarCodeReader** [comment]
Hi
Thanks for your interest.

image in the middle is the matt, which is also the global context map(GCM), which you can obtain from the model output.
image second last is from prediction stage 1, where you can get via x(1-x), x is the prediction after sigmoid. it is also the local context map (LCM)
the last image is the overlay of [image, GCM, LCM] with different alpha values.

please refer to code https://github.com/BarCodeReader/SelfReformer/blob/0b4e7cf639bd346ca8cefde1e1ddfce958b19f40/model/network.py#L90

hope it clarifies

**Comment by cenchaojun** [comment]
> Hi Thanks for your interest.
> 
> image in the middle is the matt, which is also the global context map(GCM), which you can obtain from the model output. image second last is from prediction stage 1, where you can get via x(1-x), x is the prediction after sigmoid. it is also the local context map (LCM) the last image is the overlay of [image, GCM, LCM] with different alpha values.
> 
> please refer to code
> 
> https://github.com/BarCodeReader/SelfReformer/blob/0b4e7cf639bd346ca8cefde1e1ddfce958b19f40/model/network.py#L90
> 
> hope it clarifies

thank you for your reponse. I will try it. 
best wish❤️
