### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by cenchaojun** [BarCodeReader/SelfReformer#5]
Thank you very much for your code, I tried to adjust batch_size=32 for training, but the following error occurred, what could be the reason?
RuntimeError: Trying to resize storage that is not resizable.
please.

**Comment by BarCodeReader** [comment]
seems like the error is from pytorch version, check this issue
https://github.com/pytorch/pytorch/issues/15770

**Comment by cenchaojun** [comment]
> seems like the error is from pytorch version, check this issue [pytorch/pytorch#15770](https://github.com/pytorch/pytorch/issues/15770)

thank you❤️
