### ISSUE TITLE
model/pretrain/pvt_v2_b2.pth: Git LFS bandwidth exceeded.

### ISSUE THREAD

**Issue by chhanganivarun** [BarCodeReader/SelfReformer#6]
Please provide `model/pretrain/pvt_v2_b2.pth` in some other way or buy git lfs bandwidth.

Error while cloning/ `git lfs fetch`:
```
$ git lfs fetch
Fetching main
Git LFS: (0 of 1 files) 0 B / 96.80 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/BarCodeReader/SelfReformer.git/info/lfs'
```

Hoping an early resolution 😄

**Comment by BarCodeReader** [comment]
alright, for this issue please search PVTv2 github and download their pth file instead. the LFS file here is the same as theirs.

**Comment by BarCodeReader** [comment]
alright, i uploaded to google drive [[here]](https://drive.google.com/file/d/1l5HJWXid7JETz4gxuireVXgoMjm14jEX/view?usp=sharing)

**Comment by chhanganivarun** [comment]
Thank you
