### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Lrr57** [BarCodeReader/SelfReformer#8]
Thank you very much for your code!
Is training on my own data set not supported at present？

**Comment by BarCodeReader** [comment]
Hi, thanks for your interest.
you can use your own data. just need to modify **option.py**:
https://github.com/BarCodeReader/SelfReformer/blob/e0dd8062d0f76d0eadbce635e3d72ffc904ad580/option.py#L15
and **data loader** at here:
https://github.com/BarCodeReader/SelfReformer/blob/e0dd8062d0f76d0eadbce635e3d72ffc904ad580/data/__init__.py#L36
